name: rsync-backup for DockerHub

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      APP_NAME: djkormo-rsync-backup

    steps:
    - uses: actions/checkout@v2

    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: djkormo/rsync-backup
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        workdir: .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'djkormo/rsync-backup'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
